[Feat] - Azure Blob Connector
twinfoundation/blob-storage pull request #9
Opened 2024-10-11 13:31 UTC by adriansanchezsequeira-iota

2024-10-11 14:26 UTC, obany requested changes
Couple of changes

2024-10-11 14:26 UTC, obany commented on packages/blob-storage-connector-azure/docs/changelog.md
> +## v0.0.1-next.4
Update to 6

2024-10-11 14:26 UTC, obany commented on packages/blob-storage-connector-azure/src/azureBlobStorageConnector.ts
> +		} catch {}
Probably need to throw an error in here

2024-10-11 14:28 UTC, obany commented on packages/blob-storage-connector-azure/README.md
> +The tests developed are functional tests and need an instance of Azure up and running. To run Azure locally using local stack:
this is microsoft container, not local stack

2024-10-11 14:29 UTC, obany commented on packages/blob-storage-connector-azure/README.md
> +docker run -p 10000:10000 -e AZURITE_ACCOUNTS=testAccount:testKey mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0
Can we add a name parameter to the command to keep it available like with do with the other examples

2024-10-11 14:47 UTC, adriansanchezsequeira-iota commented on packages/blob-storage-connector-azure/README.md
> +docker run -p 10000:10000 -e AZURITE_ACCOUNTS=testAccount:testKey mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0
I skip that, my bad.

--name azurite is representative enough?

2024-10-14 06:22 UTC, obany commented on packages/blob-storage-connector-azure/README.md
> +docker run -p 10000:10000 -e AZURITE_ACCOUNTS=testAccount:testKey mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0
maybe we should come up with a naming scheme for all these images to easily identify them, we can start with this one, something like `twin-blob-azure`

2024-10-14 06:38 UTC, obany approved these changes

2024-10-14 06:47 UTC, merged